version: '2'

services:
    node-sonos-http-api:
        image: webvictim/node-sonos-http-api
        container_name: node-sonos-http-api
        network_mode: host
        privileged: true
        expose:
            - 5005
        ports:
            - 5005:5005
        volumes:
            - ./custom-presets:/usr/src/app/presets
        restart: unless-stopped
